// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMassSpammer.Data;

namespace ProMassSpammer.Data.Migrations
{
    [DbContext(typeof(ProMassSpammerModel))]
    [Migration("20190922034848_dateTime2Zero")]
    partial class dateTime2Zero
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProMassSpammer.Data.Entities.DeliveryMethod", b =>
                {
                    b.Property<int>("DeliveryMethodId");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("DeliveryMethodId")
                        .HasName("PK_dbo.DeliveryMethod_DeliveryMethodId");

                    b.ToTable("DeliveryMethod","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Callsite")
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Exception")
                        .IsUnicode(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Logger")
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .IsUnicode(true);

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("Properties")
                        .IsUnicode(true);

                    b.HasKey("LogId")
                        .HasName("PK_dbo.Log_LogId");

                    b.ToTable("Log","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.MassCommunication", b =>
                {
                    b.Property<int>("MassCommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("Catalyst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("DeliveryMethod");

                    b.Property<int>("DeliveryMethodId");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<int>("MassCommunicationStatus");

                    b.Property<int>("MassCommunicationStatusId");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(78)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("MassCommunicationId")
                        .HasName("PK_dbo.MassCommunication_MassCommunicationId");

                    b.HasIndex("DeliveryMethodId")
                        .IsUnique();

                    b.HasIndex("MassCommunicationStatusId")
                        .IsUnique();

                    b.ToTable("MassCommunication","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.MassCommunicationStatus", b =>
                {
                    b.Property<int>("MassCommunicationStatusId");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MassCommunicationStatusId")
                        .HasName("PK_dbo.MassCommunicationStatus_MassCommunicationStatusId");

                    b.ToTable("MassCommunicationStatus","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("MassCommunicationId");

                    b.Property<int>("TransmissionStatus");

                    b.Property<int>("TransmissionStatusId");

                    b.Property<string>("TransmissionStatusMessage")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.HasKey("RecipientId")
                        .HasName("PK_dbo.Recipient_RecipientId");

                    b.HasIndex("MassCommunicationId");

                    b.HasIndex("TransmissionStatusId")
                        .IsUnique();

                    b.ToTable("Recipient","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.TransmissionStatus", b =>
                {
                    b.Property<int>("TransmissionStatusId");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TransmissionStatusId")
                        .HasName("PK_dbo.TransmissionStatus_TransmissionStatusId");

                    b.ToTable("TransmissionStatus","dbo");
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.MassCommunication", b =>
                {
                    b.HasOne("ProMassSpammer.Data.Entities.DeliveryMethod", "DeliveryMethodEntity")
                        .WithOne()
                        .HasForeignKey("ProMassSpammer.Data.Entities.MassCommunication", "DeliveryMethodId")
                        .HasConstraintName("FK_dbo.MassCommunication_dbo.DeliveryMethod_DeliveryMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProMassSpammer.Data.Entities.MassCommunicationStatus", "MassCommunicationStatusEntity")
                        .WithOne()
                        .HasForeignKey("ProMassSpammer.Data.Entities.MassCommunication", "MassCommunicationStatusId")
                        .HasConstraintName("FK_dbo.MassCommunication_dbo.MassCommunicationStatus_MassCommunicationStatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProMassSpammer.Data.Entities.Recipient", b =>
                {
                    b.HasOne("ProMassSpammer.Data.Entities.MassCommunication", "MassCommunication")
                        .WithMany("Recipients")
                        .HasForeignKey("MassCommunicationId")
                        .HasConstraintName("FK_dbo.Recipient_dbo.MassCommunication_MassCommunicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProMassSpammer.Data.Entities.TransmissionStatus", "TransmissionStatusEntity")
                        .WithOne()
                        .HasForeignKey("ProMassSpammer.Data.Entities.Recipient", "TransmissionStatusId")
                        .HasConstraintName("FK_dbo.Recipient_dbo.TransmissionStatus_TransmissionStatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
